"""
flag_discrepancies.py - Draft (but do not send) alert emails for discrepancies.

For every invoice whose status is a discrepancy (or needs human review), we write a
ready-to-send plain-text email to output/discrepancy_emails/. The draft names the
specific invoice, the specific PO, and the actual numbers that disagree - so a
human can glance, confirm, and forward in seconds instead of investigating from
scratch. We intentionally DON'T send: a person stays in the loop for exceptions.
"""

import re

import config


def _money(value) -> str:
    """Format a number as 'Rs. 1,03,250.00', or 'N/A' if missing."""
    if value is None:
        return "N/A"
    return f"{config.CURRENCY} {value:,.2f}"


def _safe_filename(text: str) -> str:
    """Make a filesystem-safe slug from an invoice number."""
    return re.sub(r"[^A-Za-z0-9._-]+", "_", str(text or "unknown")).strip("_")


def _draft_for(record: dict) -> tuple[str, str]:
    """Return (subject, body) for a single discrepancy record."""
    status = record["status"]
    vendor = record.get("vendor") or "Unknown Vendor"
    inv_no = record.get("invoice_number") or "Unknown"
    po_no = record.get("po_number") or "N/A"
    inv_amt = record.get("amount")
    po_amt = record.get("po_amount")

    if status == "Discrepancy: PO Not Found":
        subject = f"[Action Needed] PO not found for invoice {inv_no} ({vendor})"
        issue = (
            f"The invoice references purchase order {po_no}, but that PO number does "
            f"not exist in our PO master file. We cannot validate this invoice until "
            f"the correct PO is identified."
        )
    elif status == "Discrepancy: Amount Mismatch":
        diff = None
        if inv_amt is not None and po_amt is not None:
            diff = inv_amt - po_amt
        subject = f"[Action Needed] Amount mismatch on invoice {inv_no} ({vendor})"
        issue = (
            f"The invoice amount does not match the approved PO amount for {po_no}.\n"
            f"  - Invoice amount : {_money(inv_amt)}\n"
            f"  - PO amount      : {_money(po_amt)}\n"
            f"  - Difference     : {_money(diff)}"
        )
    elif status == "Discrepancy: Vendor Mismatch":
        subject = f"[Action Needed] Vendor mismatch on invoice {inv_no} ({vendor})"
        issue = (
            f"The amount matches, but the invoice vendor does not match the vendor "
            f"on record for {po_no}.\n"
            f"  - Invoice vendor : {vendor}\n"
            f"  - PO vendor      : {record.get('po_vendor') or 'N/A'}\n"
            f"This may mean the wrong PO was quoted, or the invoice is a duplicate "
            f"or fraudulent. Please confirm before paying."
        )
    else:  # Review: Low Confidence
        subject = f"[Please Verify] Low-confidence extraction on invoice {inv_no} ({vendor})"
        conf = record.get("confidence")
        conf_txt = f"{conf:.0%}" if isinstance(conf, (int, float)) else "low"
        issue = (
            f"The automated reader was only {conf_txt} confident about the fields it "
            f"extracted from this invoice. The PO and amount appear to match, but "
            f"please eyeball the original before approving."
        )

    body = f"""\
To: finance-payables@northwind.com
Subject: {subject}

Hi team,

An automated check flagged the following invoice for your attention:

  Vendor          : {vendor}
  Invoice Number  : {inv_no}
  Invoice Date    : {record.get('invoice_date') or 'N/A'}
  PO Number       : {po_no}
  Invoice Amount  : {_money(inv_amt)}
  Source File     : {record.get('source_file') or 'N/A'}

Issue
-----
{issue}

This is an automated draft generated by the invoice validation prototype.
No action has been taken on the invoice; please review and proceed as appropriate.

Regards,
Invoice Automation Bot
"""
    return subject, body


def flag_discrepancies(records: list[dict]) -> list[str]:
    """Write a draft email per discrepancy/review record. Returns saved paths."""
    config.EMAIL_DIR.mkdir(parents=True, exist_ok=True)

    saved = []
    for rec in records:
        if not str(rec.get("status", "")).startswith(("Discrepancy", "Review")):
            continue
        _subject, body = _draft_for(rec)
        fname = f"{_safe_filename(rec.get('invoice_number'))}.txt"
        path = config.EMAIL_DIR / fname
        path.write_text(body, encoding="utf-8")
        saved.append(str(path))
    return saved


if __name__ == "__main__":
    from extract import extract_invoices, load_local_sources
    from validate import validate_invoices

    paths = flag_discrepancies(validate_invoices(extract_invoices(load_local_sources())))
    print(f"Wrote {len(paths)} discrepancy draft(s).")
    for p in paths:
        print("  -", p)
